version: "2"
linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
  settings:
    gosec:
      excludes:
        - G115
        - G304
issues:
  max-same-issues: 20
formatters:
  enable:
    - gofmt
    - goimports
