linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - vet

run:
  timeout: 10m
